# docker run -v $PWD/..:/sources -v $PWD/binaries:/binaries cita/build
FROM ubuntu:16.04

ENV PATH $PATH:/root/.cargo/bin:/cita

COPY scripts/*.sh /tmp/
RUN /tmp/install_sys.sh	                 \
	&& /tmp/install_rust.sh				 \
	&& apt-get purge -y --auto-remove	 \
 	&& rm -rf /var/lib/apt/lists /tmp/*

WORKDIR /source
CMD /etc/init.d/rabbitmq-server restart \
	&& make release
